### PR TITLE
add subsplease

### PR DESCRIPTION
**Pull request by vvirtues**
will combine with https://github.com/almightyhak/aniyomi-extensions/pull/44 once its ready to PR

### CODE REVIEW

**Comment by vvirtues** [comment]
why was it closed?

**Comment by almightyhak** [comment]
Did you not read the readme at all?

**Comment by vvirtues** [comment]
I wanted to add the apks/icons here while everything else was in the pr I linked

**Comment by almightyhak** [comment]
Please just only upload the source code the apks are compiled through a workflow I have

**Pull request closed without merging**
